version: "3"

services:
  postgres:
    image: "postgres"
    ports:
      - 5432:5432
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "pgdata:/var/lib/postgresql/data/"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
      - POSTGRES_INITDB_ARGS=--encoding=UTF8

volumes:
  pgdata:
    name: pgdata

networks:
  default:
    name: pg
